print("Hello \"beautiful\" world")
print('I\'m Himanshu Garg')
print("line A\nline B\nline C")
print("Himanshu\tGarg")  
print("this is backslash\\")
print("this is double backslash\\\\")
print("hell\blo")